name: Deploy PBIX to Power BI Workspace

on:
  push:
    branches:
      - master

jobs:

  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Power BI PowerShell module
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt -Force -AllowClobber -Scope CurrentUser
          Import-Module MicrosoftPowerBIMgmt
      - name: Authenticate with Power BI
        run: |
          $powerBIPassword = "durga433d@87"
          $powerBIUsername = "koppada parasuram"
          $securePassword = ConvertTo-SecureString -String $powerBIPassword -AsPlainText -Force
          $credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $powerBIUsername, $securePassword
          Connect-PowerBIServiceAccount -Credential $credential
